const model = {
    app:{
        main: document.getElementById('main'),
        currentPage:'logIn',
        pages: ['homepage','logList','logInput','sleepAdvice','logIn', 'savedLog', 'editLog',],
        currentUser: 1,
        darkMode: false,
    },
    //Her kommer viewstate
    viewstate:{
        logIn: {
            name:'',
            password:'',
        },
        average:{
            averageQuality:'',
            averageLength:'', 
            averageCondition:'',
        },
        registerLog:{
            logID:'',
            date:'',
            bedtime:'',
            attemptedSleep:'',
            fellAsleep:'',
            awoken:'',
            gotUp:'',
            sleepDisturbed:'',
            timeDisturbed:'',
            napTime:'',
            quality:'',
            condition:'',
            notes:'',
            timeSleptNum: '',
            timeSlept: '',
            timeInBed: '',
        },
        selectedLog: 1,
        editLog:{
            date: '',      
            bedtime:'',
            attemptedSleep:'',
            fellAsleep:'',
            awoken:'',
            gotUp:'',
            sleepDisturbed:'',
            timeDisturbed:'',
            napTime:'',
            quality:'',
            condition:'',
            notes:'',
        },
        optimalBedtime:'',
        editBedtime: false,
    },
    //Her kommer data
    data:{
        registeredUser:[
            {userID: 1, name:'Kenneth', password:'herSkalDetSoves', optimalBedtime: '',},
            {userID: 2, name:'Bjarne', password:'007', optimalBedtime: '23:00',},
        ],
        registeredLogs:[
            //et objekt på dette nivået per bruker
            //bruker 1    
            {
            userID: 1,
            lists:[
                    //første logg
                    {
                        logID: 1,
                        date: '2025-10-10',
                        bedtime:'22:00',
                        attemptedSleep:'22:30',
                        fellAsleep:'23:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 465,
                        timeSlept:'7t 45min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 3,
                        condition: 4,
                        notes:'Våknet bare en gang i natt! Dette er en forbedring fra i går :)',
                    },
                    //andre logg
                    {
                        logID: 2,   
                        date: '2025-10-11',
                        bedtime:'22:00',
                        attemptedSleep:'22:30',
                        fellAsleep:'23:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 475,
                        timeSlept:'7t 55min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 3,
                        condition: 5,
                        notes:'Veldig deilig søvn',
                    },
                    {
                        logID: 3,   
                        date: '2025-10-12',
                        bedtime:'21:00',
                        attemptedSleep:'21:30',
                        fellAsleep:'22:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 495,
                        timeSlept:'7t 55min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 2,
                        condition: 4,
                        notes:'Veldig deilig søvn',
                    },
                    {
                        logID: 4,   
                        date: '2025-10-13',
                        bedtime:'22:00',
                        attemptedSleep:'22:30',
                        fellAsleep:'23:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 455,
                        timeSlept:'7t 55min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 4,
                        condition: 5,
                        notes:'Veldig deilig søvn',
                    },
                    {
                        logID: 5,   
                        date: '2025-10-14',
                        bedtime:'22:00',
                        attemptedSleep:'22:30',
                        fellAsleep:'23:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 475,
                        timeSlept:'7t 55min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 3,
                        condition: 5,
                        notes:'Veldig deilig søvn',
                    },
                    {
                        logID: 6,   
                        date: '2025-10-15',
                        bedtime:'22:00',
                        attemptedSleep:'22:30',
                        fellAsleep:'23:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 460,
                        timeSlept:'7t 55min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 3,
                        condition: 4,
                        notes:'Veldig deilig søvn',
                    },
                    {
                        logID: 7,   
                        date: '2025-10-16',
                        bedtime:'22:00',
                        attemptedSleep:'22:30',
                        fellAsleep:'23:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 465,
                        timeSlept:'7t 55min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 4,
                        condition: 3,
                        notes:'Veldig deilig søvn',
                    },
                    {
                        logID: 8,   
                        date: '2025-10-17',
                        bedtime:'22:00',
                        attemptedSleep:'22:30',
                        fellAsleep:'23:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 150,
                        timeSlept:'7t 55min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 1,
                        condition: 1,
                        notes:'Veldig deilig søvn',
                    },
                ],
            },
            //bruker 2
            {
                userID: 2,
                lists:[
                    //første logg
                    {
                        logID: 1,
                        date: '2025-10-21',
                        bedtime:'22:00',
                        attemptedSleep:'22:30',
                        fellAsleep:'23:00',
                        awoken:'07:00',
                        gotUp:'07:15',
                        sleepDisturbed:'1',
                        timeDisturbed:'15',
                        timeSleptNum: 465,
                        timeSlept:'7t 45min',
                        timeInBed:'9t 15min',
                        napTime:'25',
                        quality: 3,
                        condition: 4,
                        notes:'Veldig dårlig søvn',
                    },
                ],
            },
        ],
    },
}

//HEiHEi!
//Boo!